name: Move Tests

on:
  push:
    branches:
      - main
      - '**'  # Run on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Sui CLI
        run: |
          wget https://github.com/MystenLabs/sui/releases/download/testnet-v1.61.2/sui-testnet-v1.61.2-ubuntu-x86_64.tgz
          tar -xvzf sui-testnet-v1.61.2-ubuntu-x86_64.tgz
          sudo mv sui /usr/local/bin/
          sui --version
      
      - name: Build Move project
        run: sui move build
        working-directory: ./module_1

      - name: Run Move tests
        run: sui move test
        working-directory: ./module_1
